version: 2
jobs:
  build_web:
    working_directory: ~/CEN4010-TeamProject
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout

  build_api:
    working_directory: ~/CEN4010-TeamProject
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout

  deploy_web:
    working_directory: ~/CEN4010-TeamProject
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Install bsdmainutils
          command: |
            apt-get update
            apt-get install bsdmainutils
      - checkout
      - run:
          name: Configure git identity
          command: |
            git config --global user.email "circleci@admin.com"
            git config --global user.name "CircleCI"
      - run:
          name: Decrypt files
          command: |
            chmod +x transcrypt
            git add -A
            git commit -m "Prepared transcrypt"
            ./transcrypt -c $TRANSCRYPT_CRYPT -p $TRANSCRYPT_PASSWORD -y
            ./transcrypt -u -y
      - run:
          name: Copy contents of web directory
          command: |
            cp -a web/. ./
            rm -r api
            rm -r web
      - run:
          name: Commit changes
          command: |
            git add -A
            git commit -m "Prepared project to be deployed to web server"
      - run:
          name: Deploy to Heroku
          command: |
            git push -u -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_FRONTEND_APP_NAME.git $CIRCLE_BRANCH:master
            
  deploy_api:
    working_directory: ~/CEN4010-TeamProject
    docker:
      - image: buildpack-deps:trusty
    steps:
      - run:
          name: Install bsdmainutils
          command: |
            apt-get update
            apt-get install bsdmainutils
      - checkout
      - run:
          name: Configure git identity
          command: |
            git config --global user.email "circleci@admin.com"
            git config --global user.name "CircleCI"
      - run:
          name: Decrypt files
          command: |
            chmod +x transcrypt
            git add -A
            git commit -m "Prepared transcrypt"
            ./transcrypt -c $TRANSCRYPT_CRYPT -p $TRANSCRYPT_PASSWORD -y
            ./transcrypt -u -y
      - run:
          name: Copy contents of API directory
          command: |
            cp -a api/. ./
            rm -r api
            rm -r web
      - run:
          name: Commit changes
          command: |
            git add -A
            git commit -m "Prepared project to be deployed to API server"
      - run:
          name: Deploy to Heroku
          command: |
            git push -u -f https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_BACKEND_APP_NAME.git $CIRCLE_BRANCH:master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build_web
      - build_api
      - deploy_web:
          requires:
            - build_web
            - build_api
            - deploy_api
          filters:
            branches:
              only: master
      - deploy_api:
          requires:
            - build_web
            - build_api
          filters:
            branches:
              only: master