version: 2
jobs:
  build_front_end:
    working_directory: ~/CEN4010-TeamProject
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout

  build_back_end:
    working_directory: ~/CEN4010-TeamProject
    docker:
      - image: microsoft/dotnet:2.1-sdk
    steps:
      - checkout

workflows:
  version: 2
  build:
    jobs:
      - build_front_end
      - build_back_end